import type { LucideIcon } from 'lucide-react'
import {
  Book,
  BookOpen,
  Briefcase,
  Code,
  File,
  FileText,
  Film,
  Globe,
  GraduationCap,
  Image as ImageIcon,
  Mail,
  MapIcon,
  MessageSquare,
  Mic,
  Newspaper,
  NotebookPen,
  Presentation,
  Scale,
  StickyNote,
  Video,
} from 'lucide-react'

const ICON_BY_TYPE: Record<string, LucideIcon> = {
  artwork: ImageIcon,
  audioRecording: Mic,
  bill: Scale,
  blogPost: Globe,
  book: Book,
  bookSection: BookOpen,
  case: Scale,
  computerProgram: Code,
  conferencePaper: Presentation,
  dictionaryEntry: BookOpen,
  document: FileText,
  email: Mail,
  encyclopediaArticle: BookOpen,
  film: Film,
  forumPost: MessageSquare,
  hearing: Scale,
  instantMessage: MessageSquare,
  interview: Mic,
  journalArticle: FileText,
  letter: Mail,
  magazineArticle: Newspaper,
  manuscript: FileText,
  map: MapIcon,
  newspaperArticle: Newspaper,
  note: StickyNote,
  patent: Briefcase,
  podcast: Mic,
  preprint: NotebookPen,
  presentation: Presentation,
  radioBroadcast: Mic,
  report: FileText,
  statute: Scale,
  thesis: GraduationCap,
  tvBroadcast: Film,
  videoRecording: Video,
  webpage: Globe,
}

export const getItemTypeIcon = (itemType: string): LucideIcon => {
  return ICON_BY_TYPE[itemType] ?? File
}
