import pkg from '../package.json'
import { PropertyPreset } from './interfaces'

export const PLUGIN_ID = pkg.logseq.id

export const ZOTERO_PROP = `:plugin.property.${PLUGIN_ID}`
export const ZOTERO_CODE_PROP = `${ZOTERO_PROP}/zotero-code`
export const ZOTERO_ATTACHMENT_KEY_PROP = `${ZOTERO_PROP}/zotero-attachment-key`
export const ZOT_URL = 'http://127.0.0.1:23119/api/users/0'
export const ZOTERO_LIBRARY_ITEM = 'zotero://select/library/items?itemKey='

// Default base reference tag every imported page carries (the `zotTag` setting's
// fallback). Single-sourced here — consumers read `logseq.settings?.zotTag ??
// ZOT_TAG_DEFAULT` — so the import + query flow doesn't depend on a 'Reference'
// literal scattered across files. Mirrors the schema default in `settings.ts`.
export const ZOT_TAG_DEFAULT = 'Reference'

// Logseq's desktop HTTP API server (Settings → Features → HTTP APIs Server).
// The annotation write path POSTs a Transit-encoded sqlite.build payload to
// `${base}/api` (method `logseq.cli.import_edn`) — the only route that can write
// the closed-value `hl-color` ref + `hl-value` map the plugin Editor API can't.
export const LOGSEQ_API_BASE_DEFAULT = 'http://127.0.0.1:12315'

// Attachments tab settings — defaults mirror the schema in `settings.ts`.
// Kept here so the import flow doesn't depend on string literals scattered
// across files.
export const ATTACHMENTS_BLOCK_NAME_DEFAULT = 'Attachments'
export const ATTACHMENT_IMPORT_MODES = ['PDFs only', 'All attachments'] as const
export type AttachmentImportMode = (typeof ATTACHMENT_IMPORT_MODES)[number]
export const ATTACHMENT_EXTERNAL_PDF_LABEL_DEFAULT = 'Open PDF Outside Logseq'

export const BASE_QUERY = {
  sort: 'dateAdded',
  direction: 'desc',
  limit: 100,
}

// Coalesces in-flight typing into one server query. Tight because Zotero's
// local API is fast (single-digit ms on localhost) — this is just enough to
// skip the noise of fast-typed intermediate keystrokes, not to mask latency.
export const DEBOUNCE_DELAY = 80

// Upper bound for items fetched per collection / saved search in a single
// request. The local Zotero API has no hard `limit` cap; batch import targets
// curated collections rather than whole libraries, so a generous flat limit
// avoids pagination. A container larger than this would be truncated.
export const BATCH_FETCH_LIMIT = 1000

// `mapItems` walks a big collection / saved search in growing chunks,
// streaming each chunk back (via `onChunk`) with a yield in between, so the
// list paints progressively instead of in one jump. The first chunk is
// deliberately small for an instant first paint; later chunks double — up to
// `MAP_CHUNK_MAX` — so a large container settles in a handful of renders.
export const MAP_CHUNK_INITIAL = 10
export const MAP_CHUNK_MAX = 80

// Properties displayed first on the Zotero tag. Logseq orders tag properties
// by the sequence in which `addTagProperty` is called, so these are added to
// the tag before anything else. Kept in camelCase to match the preset lists;
// `convertPropToKebabCase` runs at schema setup.
export const PROP_PRIORITY_ORDER = [
  'authors',
  'shortTitle',
  'title',
  'url',
  'date',
  'dateAdded',
] as const

// Properties shown inline on an imported page by default. Everything else is
// marked "hide by default", so it's tucked into Logseq's collapsed "Hidden
// properties" group and the page reads as notes, not a metadata dump. Kebab
// form — compared against the kebab `prop` in `set-logseqdb-schema`.
// Opinionated default for now; making it user-configurable is a TODO (dev-notes/settings.md).
export const VISIBLE_BY_DEFAULT_PROPS = new Set<string>([
  'authors',
  'title',
  'url',
  'date',
  'date-added',
])

// Property presets - each tier includes all properties from the tier(s) below it
export const PROP_PRESET_ESSENTIALS = [
  'title',
  'itemType',
  'authors',
  'creators',
  'date',
  'dateAdded',
  'url',
  'citationKey',
  'libraryLink',
  'DOI',
  'ISSN',
  'libraryCatalog',
  'repository',
  'archiveID',
  'extra',
  'shortTitle',
  'publisher',
  'publicationTitle',
  'proceedingsTitle',
  'volume',
  'issue',
  'journalAbbreviation',
  'websiteTitle',
  'blogTitle',
  'language',
  'tags',
] as const

export const PROP_PRESETS: Record<
  Exclude<PropertyPreset, 'Custom' | 'Full'>,
  readonly string[]
> = {
  Essentials: PROP_PRESET_ESSENTIALS,
}

// Display names shown in the Logseq UI for each property. The key is the
// Zotero API field name (camelCase), or the plugin-internal kebab name for
// the three `zotero-*` properties. The value is what appears as the property
// label in the tag schema and on each page. Edit values here to customize.
export const PROP_DISPLAY_NAMES: Record<string, string> = {
  abstractNote: 'Abstract',
  accessDate: 'Accessed',
  annotationAuthorName: 'Annotation Author',
  annotationColor: 'Annotation Color',
  annotationComment: 'Annotation Comment',
  annotationPageLabel: 'Annotation Page Label',
  annotationPosition: 'Annotation Position',
  annotationSortIndex: 'Annotation Sort Index',
  annotationText: 'Annotation Text',
  annotationType: 'Annotation Type',
  applicationNumber: 'Application Number',
  archive: 'Archive',
  archiveID: 'Archive ID',
  archiveLocation: 'Loc. in Archive',
  artworkMedium: 'Artwork Medium',
  artworkSize: 'Artwork Size',
  assignee: 'Assignee',
  audioFileType: 'Audio File Type',
  audioRecordingFormat: 'Audio Recording Format',
  authors: 'Authors',
  billNumber: 'Bill Number',
  blogTitle: 'Blog Title',
  bookTitle: 'Book Title',
  callNumber: 'Call Number',
  caseName: 'Case Name',
  charset: 'Charset',
  citationKey: 'Citation Key',
  code: 'Code',
  codeNumber: 'Code Number',
  codePages: 'Code Pages',
  codeVolume: 'Code Volume',
  collections: 'Collections',
  committee: 'Committee',
  company: 'Company',
  contentType: 'Content Type',
  country: 'Country',
  court: 'Court',
  creators: 'Creators',
  date: 'Date',
  dateAdded: 'Date Added',
  dateModified: 'Modified',
  day: 'Day',
  distributor: 'Distributor',
  docketNumber: 'Docket Number',
  DOI: 'DOI',
  edition: 'Edition',
  email: 'Email',
  encyclopediaTitle: 'Encyclopedia Title',
  extra: 'Extra',
  filingDate: 'Filing Date',
  filename: 'Filename',
  firstPage: 'First Page',
  forumTitle: 'Forum Title',
  genre: 'Genre',
  history: 'History',
  institution: 'Institution',
  ISBN: 'ISBN',
  ISSN: 'ISSN',
  issue: 'Issue',
  issueDate: 'Issue Date',
  issuingAuthority: 'Issuing Authority',
  itemType: 'Item Type',
  journalAbbreviation: 'Journal Abbreviation',
  key: 'Key',
  label: 'Label',
  language: 'Language',
  legalStatus: 'Legal Status',
  legislativeBody: 'Legislative Body',
  libraryCatalog: 'Library Catalog',
  libraryLink: 'Library Link',
  license: 'License',
  linkMode: 'Link Mode',
  manuscriptType: 'Manuscript Type',
  mapType: 'Map Type',
  md5: 'MD5',
  medium: 'Medium',
  meetingName: 'Meeting Name',
  meetingPlace: 'Meeting Place',
  month: 'Month',
  mtime: 'Mtime',
  network: 'Network',
  note: 'Note',
  number: 'Number',
  numberOfVolumes: '# of Volumes',
  numPages: '# of Pages',
  pages: 'Pages',
  parentItem: 'Parent Item',
  patentNumber: 'Patent Number',
  place: 'Place',
  postType: 'Post Type',
  presentationType: 'Presentation Type',
  proceedingsTitle: 'Proceedings Title',
  publicationTitle: 'Publication Title',
  publisher: 'Publisher',
  radioProgramTitle: 'Radio Program Title',
  references: 'References',
  relations: 'Relations',
  reportNumber: 'Report Number',
  reportType: 'Report Type',
  repository: 'Repository',
  rights: 'Rights',
  runningTime: 'Running Time',
  scale: 'Scale',
  section: 'Section',
  series: 'Series',
  seriesNumber: 'Series Number',
  seriesText: 'Series Text',
  seriesTitle: 'Series Title',
  shortTitle: 'Short Title',
  studio: 'Studio',
  subject: 'Subject',
  system: 'System',
  tags: 'Tags',
  thesisType: 'Thesis Type',
  title: 'Title',
  tvProgramTitle: 'TV Program Title',
  university: 'University',
  url: 'URL',
  version: 'Version',
  versionNumber: 'Version Number',
  videoRecordingFormat: 'Video Recording Format',
  volume: 'Volume',
  websiteTitle: 'Website Title',
  websiteType: 'Website Type',
  year: 'Year',
  // Plugin-internal properties (already kebab-cased; not Zotero API fields)
  'zotero-code': 'Zotero Code',
  'zotero-attachment-key': 'Zotero Attachment Key',
}

// Short descriptions shown beneath each property in the Logseq tag schema UI.
// Same keying as PROP_DISPLAY_NAMES: the Zotero API field name (camelCase), or
// the plugin-internal kebab name for the three `zotero-*` properties. Applied
// to the property block via `logseq.property/description` at schema setup.
// Edit values here to customize.
export const PROP_DESCRIPTIONS: Record<string, string> = {
  abstractNote: "The item's abstract or summary",
  accessDate: 'Date the reference was accessed',
  annotationAuthorName: 'Author of the annotation',
  annotationColor: 'Highlight color of the annotation',
  annotationComment: 'Comment attached to the annotation',
  annotationPageLabel: 'Page label where the annotation appears',
  annotationPosition: 'Position of the annotation within the file',
  annotationSortIndex: 'Index used to order annotations within an item',
  annotationText: 'Highlighted or extracted text of the annotation',
  annotationType: 'Kind of annotation (highlight, note, image, etc.)',
  applicationNumber: 'Patent application number',
  archive: 'Archive holding the item',
  archiveID: 'Identifier of the item within the archive',
  archiveLocation: 'Location of the item within the archive',
  artworkMedium: 'Medium or material of the artwork',
  artworkSize: 'Dimensions of the artwork',
  assignee: 'Person or entity the patent is assigned to',
  audioFileType: 'File format of the audio recording',
  audioRecordingFormat: 'Format of the audio recording',
  authors: '',
  billNumber: 'Number identifying the bill',
  blogTitle: '',
  bookTitle: 'Title of the book containing this section',
  callNumber: 'Library call number for the item',
  caseName: 'Name of the legal case',
  charset: 'Character encoding of the attachment',
  citationKey: 'Citation key used in references (e.g. BibTeX)',
  code: 'Name of the code or legal statute',
  codeNumber: 'Number of the code or statute',
  codePages: 'Page range within the code',
  codeVolume: 'Volume of the code',
  collections: 'Zotero collections the item belongs to',
  committee: 'Committee associated with the document',
  company: 'Company that produced the item',
  contentType: 'MIME type of the attachment',
  country: 'Country of publication or jurisdiction',
  court: 'Court that decided the case',
  creators: 'All contributors and their roles',
  date: 'Publication date of the item',
  dateAdded: 'Date the item was added to Zotero',
  dateModified: 'Date the item was last modified in Zotero',
  day: 'Day component of the date',
  distributor: 'Distributor of the item',
  docketNumber: 'Court docket number',
  DOI: 'Digital Object Identifier',
  edition: 'Edition of the work',
  email: 'Contact email address',
  encyclopediaTitle: 'Title of the encyclopedia',
  extra: 'Free-form extra metadata',
  filingDate: 'Date the patent was filed',
  filename: 'Name of the attached file',
  firstPage: 'First page of the cited material',
  forumTitle: 'Title of the forum or listserv',
  genre: 'Genre or category of the work',
  history: 'Procedural history of the case',
  institution: 'Institution that issued the report',
  ISBN: 'International Standard Book Number',
  ISSN: 'International Standard Serial Number',
  issue: 'Issue number of the publication',
  issueDate: 'Date the patent was issued',
  issuingAuthority: 'Authority that issued the patent',
  itemType: 'Zotero item type (book, journal article, etc.)',
  journalAbbreviation: 'Abbreviated journal title',
  key: 'Zotero item key',
  label: 'Record label or publisher imprint',
  language: '',
  legalStatus: 'Legal status of the patent',
  legislativeBody: 'Legislative body responsible for the bill',
  libraryCatalog: 'Catalog or database the item came from',
  libraryLink: 'Link to open the item in Zotero',
  license: 'License governing the item',
  linkMode: 'How the attachment is linked or stored',
  manuscriptType: 'Type of manuscript',
  mapType: 'Type of map',
  md5: 'MD5 checksum of the attached file',
  medium: 'Medium of the recording or artwork',
  meetingName: 'Name of the meeting or conference',
  meetingPlace: 'Location of the meeting',
  month: 'Month component of the date',
  mtime: 'Last-modified time of the attached file',
  network: 'Broadcast network',
  note: 'Note content',
  number: 'Generic number identifying the item',
  numberOfVolumes: 'Total number of volumes',
  numPages: 'Total number of pages',
  pages: 'Page range of the item',
  parentItem: 'Key of the parent item',
  patentNumber: 'Patent number',
  place: 'Place of publication',
  postType: 'Type of forum post',
  presentationType: 'Type of presentation',
  proceedingsTitle: 'Title of the conference proceedings',
  publicationTitle: 'Title of the publication (journal, magazine, etc.)',
  publisher: 'Publisher of the item',
  radioProgramTitle: 'Title of the radio program',
  references: 'Works referenced by the item',
  relations: 'Related Zotero items',
  reportNumber: 'Number of the report',
  reportType: 'Type of report',
  repository: 'Repository hosting the item',
  rights: 'Copyright or rights information',
  runningTime: 'Duration of the recording',
  scale: 'Scale of the map',
  section: 'Section of the newspaper or code',
  series: 'Series the item belongs to',
  seriesNumber: 'Number within the series',
  seriesText: 'Additional series information',
  seriesTitle: 'Title of the series',
  shortTitle: '',
  studio: 'Studio that produced the film',
  subject: 'Subject of the letter or message',
  system: 'Operating system or platform',
  tags: 'Zotero tags applied to the item',
  thesisType: 'Type of thesis or dissertation',
  title: '',
  tvProgramTitle: 'Title of the TV program',
  university: 'University that granted the degree',
  url: '',
  version: 'Version of the software or item',
  versionNumber: 'Version number of the software',
  videoRecordingFormat: 'Format of the video recording',
  volume: 'Volume number',
  websiteTitle: '',
  websiteType: 'Type of website',
  year: 'Year component of the date',
  // Plugin-internal properties (already kebab-cased; not Zotero API fields)
  'zotero-code': 'Zotero item key linking this page to Zotero',
  'zotero-attachment-key':
    'Zotero key of the attachment, used to sync annotations',
}

// TODO: Wtf is the point of this?
export const ZOT_DATA_KEY_MAP = {
  abstractNote: true,
  accessDate: true,
  annotationAuthorName: true,
  annotationColor: true,
  annotationComment: true,
  annotationPageLabel: true,
  annotationPosition: true,
  annotationSortIndex: true,
  annotationText: true,
  annotationType: true,
  applicationNumber: true,
  archive: true,
  archiveID: true,
  archiveLocation: true,
  artworkMedium: true,
  artworkSize: true,
  assignee: true,
  audioFileType: true,
  audioRecordingFormat: true,
  billNumber: true,
  blogTitle: true,
  bookTitle: true,
  callNumber: true,
  caseName: true,
  charset: true,
  citationKey: true,
  code: true,
  codeNumber: true,
  codePages: true,
  codeVolume: true,
  collections: true,
  committee: true,
  company: true,
  contentType: true,
  country: true,
  court: true,
  authors: true,
  creators: true,
  date: true,
  dateAdded: true,
  dateModified: true,
  day: true,
  distributor: true,
  docketNumber: true,
  DOI: true,
  edition: true,
  email: true,
  encyclopediaTitle: true,
  extra: true,
  filingDate: true,
  filename: true,
  firstPage: true,
  forumTitle: true,
  genre: true,
  history: true,
  institution: true,
  ISBN: true,
  ISSN: true,
  issue: true,
  issueDate: true,
  issuingAuthority: true,
  itemType: true,
  journalAbbreviation: true,
  key: true,
  label: true,
  language: true,
  legalStatus: true,
  legislativeBody: true,
  libraryCatalog: true,
  libraryLink: true,
  license: true,
  linkMode: true,
  manuscriptType: true,
  mapType: true,
  md5: true,
  medium: true,
  meetingName: true,
  meetingPlace: true,
  month: true,
  mtime: true,
  network: true,
  note: true,
  numberOfVolumes: true,
  number: true,
  numPages: true,
  pages: true,
  parentItem: true,
  patentNumber: true,
  place: true,
  postType: true,
  presentationType: true,
  proceedingsTitle: true,
  publicationTitle: true,
  publisher: true,
  radioProgramTitle: true,
  references: true,
  relations: true,
  reportNumber: true,
  reportType: true,
  repository: true,
  rights: true,
  runningTime: true,
  scale: true,
  section: true,
  series: true,
  seriesNumber: true,
  seriesText: true,
  seriesTitle: true,
  shortTitle: true,
  studio: true,
  subject: true,
  system: true,
  tags: true,
  thesisType: true,
  title: true,
  tvProgramTitle: true,
  university: true,
  url: true,
  version: true,
  versionNumber: true,
  videoRecordingFormat: true,
  volume: true,
  websiteTitle: true,
  websiteType: true,
  year: true,
}
