import { PropertyPreset } from './interfaces'

export const ZOTERO_PROP = ':plugin.property.logseq-zoterolocal-plugin'
export const ZOTERO_CODE_PROP =
  ':plugin.property.logseq-zoterolocal-plugin/zotero-code'
export const ZOTERO_LAST_SYNC_PROP =
  ':plugin.property.logseq-zoterolocal-plugin/zotero-last-sync'
export const ZOTERO_ATTACHMENT_KEY_PROP =
  ':plugin.property.logseq-zoterolocal-plugin/zotero-attachment-key'
export const ZOT_URL = 'http://127.0.0.1:23119/api/users/0'
export const ZOTERO_LIBRARY_ITEM = 'zotero://select/library/items?itemKey='
export const BASE_QUERY = {
  sort: 'dateAdded',
  direction: 'desc',
  limit: 100,
}

export const DEBOUNCE_DELAY = 400

// Properties displayed first on the Zotero tag. Logseq orders tag properties
// by the sequence in which `addTagProperty` is called, so these are added to
// the tag before anything else. Kept in camelCase to match the preset lists;
// `convertPropToKebabCase` runs at schema setup.
export const PROP_PRIORITY_ORDER = [
  'authors',
  'shortTitle',
  'title',
  'url',
  'date',
  'dateAdded',
] as const

// Property presets - each tier includes all properties from the tier(s) below it
export const PROP_PRESET_ESSENTIALS = [
  'title',
  'itemType',
  'authors',
  'creators',
  'date',
  'dateAdded',
  'url',
  'citationKey',
  'libraryLink',
  'DOI',
  'ISSN',
  'libraryCatalog',
  'repository',
  'archiveID',
  'extra',
  'shortTitle',
  'publicationTitle',
  'proceedingsTitle',
  'volume',
  'issue',
  'journalAbbreviation',
  'websiteTitle',
  'blogTitle',
  'language',
  'tags',
] as const

export const PROP_PRESETS: Record<
  Exclude<PropertyPreset, 'Custom' | 'Full'>,
  readonly string[]
> = {
  Essentials: PROP_PRESET_ESSENTIALS,
}

// Display names shown in the Logseq UI for each property. The key is the
// Zotero API field name (camelCase), or the plugin-internal kebab name for
// the three `zotero-*` properties. The value is what appears as the property
// label in the tag schema and on each page. Edit values here to customize.
export const PROP_DISPLAY_NAMES: Record<string, string> = {
  abstractNote: 'Abstract',
  accessDate: 'Accessed',
  annotationAuthorName: 'Annotation Author',
  annotationColor: 'Annotation Color',
  annotationComment: 'Annotation Comment',
  annotationPageLabel: 'Annotation Page Label',
  annotationPosition: 'Annotation Position',
  annotationSortIndex: 'Annotation Sort Index',
  annotationText: 'Annotation Text',
  annotationType: 'Annotation Type',
  applicationNumber: 'Application Number',
  archive: 'Archive',
  archiveID: 'Archive ID',
  archiveLocation: 'Loc. in Archive',
  artworkMedium: 'Artwork Medium',
  artworkSize: 'Artwork Size',
  assignee: 'Assignee',
  audioFileType: 'Audio File Type',
  audioRecordingFormat: 'Audio Recording Format',
  authors: 'Authors',
  billNumber: 'Bill Number',
  blogTitle: 'Blog Title',
  bookTitle: 'Book Title',
  callNumber: 'Call Number',
  caseName: 'Case Name',
  charset: 'Charset',
  citationKey: 'Citation Key',
  code: 'Code',
  codeNumber: 'Code Number',
  codePages: 'Code Pages',
  codeVolume: 'Code Volume',
  collections: 'Collections',
  committee: 'Committee',
  company: 'Company',
  contentType: 'Content Type',
  country: 'Country',
  court: 'Court',
  creators: 'Creators',
  date: 'Date',
  dateAdded: 'Date Added',
  dateModified: 'Modified',
  day: 'Day',
  distributor: 'Distributor',
  docketNumber: 'Docket Number',
  DOI: 'DOI',
  edition: 'Edition',
  email: 'Email',
  encyclopediaTitle: 'Encyclopedia Title',
  extra: 'Extra',
  filingDate: 'Filing Date',
  filename: 'Filename',
  firstPage: 'First Page',
  forumTitle: 'Forum Title',
  genre: 'Genre',
  history: 'History',
  institution: 'Institution',
  ISBN: 'ISBN',
  ISSN: 'ISSN',
  issue: 'Issue',
  issueDate: 'Issue Date',
  issuingAuthority: 'Issuing Authority',
  itemType: 'Item Type',
  journalAbbreviation: 'Journal Abbreviation',
  key: 'Key',
  label: 'Label',
  language: 'Language',
  legalStatus: 'Legal Status',
  legislativeBody: 'Legislative Body',
  libraryCatalog: 'Library Catalog',
  libraryLink: 'Library Link',
  license: 'License',
  linkMode: 'Link Mode',
  manuscriptType: 'Manuscript Type',
  mapType: 'Map Type',
  md5: 'MD5',
  medium: 'Medium',
  meetingName: 'Meeting Name',
  meetingPlace: 'Meeting Place',
  month: 'Month',
  mtime: 'Mtime',
  network: 'Network',
  note: 'Note',
  number: 'Number',
  numberOfVolumes: '# of Volumes',
  numPages: '# of Pages',
  pages: 'Pages',
  parentItem: 'Parent Item',
  patentNumber: 'Patent Number',
  place: 'Place',
  postType: 'Post Type',
  presentationType: 'Presentation Type',
  proceedingsTitle: 'Proceedings Title',
  publicationTitle: 'Publication Title',
  publisher: 'Publisher',
  radioProgramTitle: 'Radio Program Title',
  references: 'References',
  relations: 'Relations',
  reportNumber: 'Report Number',
  reportType: 'Report Type',
  repository: 'Repository',
  rights: 'Rights',
  runningTime: 'Running Time',
  scale: 'Scale',
  section: 'Section',
  series: 'Series',
  seriesNumber: 'Series Number',
  seriesText: 'Series Text',
  seriesTitle: 'Series Title',
  shortTitle: 'Short Title',
  studio: 'Studio',
  subject: 'Subject',
  system: 'System',
  tags: 'Tags',
  thesisType: 'Thesis Type',
  title: 'Title',
  tvProgramTitle: 'TV Program Title',
  university: 'University',
  url: 'URL',
  version: 'Version',
  versionNumber: 'Version Number',
  videoRecordingFormat: 'Video Recording Format',
  volume: 'Volume',
  websiteTitle: 'Website Title',
  websiteType: 'Website Type',
  year: 'Year',
  // Plugin-internal properties (already kebab-cased; not Zotero API fields)
  'zotero-code': 'Zotero Code',
  'zotero-last-sync': 'Zotero Last Sync',
  'zotero-attachment-key': 'Zotero Attachment Key',
}

export const ZOT_DATA_KEY_MAP = {
  abstractNote: true,
  accessDate: true,
  annotationAuthorName: true,
  annotationColor: true,
  annotationComment: true,
  annotationPageLabel: true,
  annotationPosition: true,
  annotationSortIndex: true,
  annotationText: true,
  annotationType: true,
  applicationNumber: true,
  archive: true,
  archiveID: true,
  archiveLocation: true,
  artworkMedium: true,
  artworkSize: true,
  assignee: true,
  audioFileType: true,
  audioRecordingFormat: true,
  billNumber: true,
  blogTitle: true,
  bookTitle: true,
  callNumber: true,
  caseName: true,
  charset: true,
  citationKey: true,
  code: true,
  codeNumber: true,
  codePages: true,
  codeVolume: true,
  collections: true,
  committee: true,
  company: true,
  contentType: true,
  country: true,
  court: true,
  authors: true,
  creators: true,
  date: true,
  dateAdded: true,
  dateModified: true,
  day: true,
  distributor: true,
  docketNumber: true,
  DOI: true,
  edition: true,
  email: true,
  encyclopediaTitle: true,
  extra: true,
  filingDate: true,
  filename: true,
  firstPage: true,
  forumTitle: true,
  genre: true,
  history: true,
  institution: true,
  ISBN: true,
  ISSN: true,
  issue: true,
  issueDate: true,
  issuingAuthority: true,
  itemType: true,
  journalAbbreviation: true,
  key: true,
  label: true,
  language: true,
  legalStatus: true,
  legislativeBody: true,
  libraryCatalog: true,
  libraryLink: true,
  license: true,
  linkMode: true,
  manuscriptType: true,
  mapType: true,
  md5: true,
  medium: true,
  meetingName: true,
  meetingPlace: true,
  month: true,
  mtime: true,
  network: true,
  note: true,
  numberOfVolumes: true,
  number: true,
  numPages: true,
  pages: true,
  parentItem: true,
  patentNumber: true,
  place: true,
  postType: true,
  presentationType: true,
  proceedingsTitle: true,
  publicationTitle: true,
  publisher: true,
  radioProgramTitle: true,
  references: true,
  relations: true,
  reportNumber: true,
  reportType: true,
  repository: true,
  rights: true,
  runningTime: true,
  scale: true,
  section: true,
  series: true,
  seriesNumber: true,
  seriesText: true,
  seriesTitle: true,
  shortTitle: true,
  studio: true,
  subject: true,
  system: true,
  tags: true,
  thesisType: true,
  title: true,
  tvProgramTitle: true,
  university: true,
  url: true,
  version: true,
  versionNumber: true,
  videoRecordingFormat: true,
  volume: true,
  websiteTitle: true,
  websiteType: true,
  year: true,
}
